version: '3'

services:
  etl:
    build: .
    depends_on:
      - mysql
    networks:
      - app-tier
    volumes:
      - .:/prueba_pragma

  mysql:
    image: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: pragma
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
